input.onButtonPressed(Button.A, function () {
    serial.writeLine(convertToText(input.temperature()))
    sensor = input.temperature()
})
serial.onDataReceived(serial.delimiters(Delimiters.CarriageReturn), function () {
    serial.writeString("@")
})
let sensor = 0
serial.redirect(
SerialPin.USB_TX,
SerialPin.USB_RX,
BaudRate.BaudRate115200
)
serial.redirectToUSB()
basic.forever(function () {
    pins.i2cWriteNumber(
    46,
    107,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    111,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    110,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    110,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    110,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    105,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    116,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    105,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    119,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    97,
    NumberFormat.UInt8BE,
    false
    )
    pins.i2cWriteNumber(
    46,
    13,
    NumberFormat.UInt8BE,
    false
    )
    basic.pause(1000)
    serial.writeString("a")
})
