def on_forever():
    pins.i2c_write_number(46, 0x6b, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x6f, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x6e, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x6e, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x6e, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x69, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x74, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x69, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x77, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 0x61, NumberFormat.UINT8_BE, False)
    pins.i2c_write_number(46, 13, NumberFormat.UINT8_BE, False)
    basic.pause(1000)
basic.forever(on_forever)
